#!/bin/sh
echo "\bfinding old message\n" 
find /mailstore/user/mailstore/ -type file -mtime +180 -exec rm {} \;
#find /mailstore/user/plm/ -type file -mtime +30 -exec mv {} /home/sharov/old/ \;
echo "restoring database"
su -l cyrus -c '/usr/local/cyrus/bin/reconstruct -r user.mailstore'
#find /mailstore/user/mailstore/ -type file -mtime +31 -print0 | xargs -0 rm
